[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]

[target.wasm32-wasi]
rustflags = ["--cfg=web_sys_unstable_apis"]

[build]
# target = "wasm32-unknown-unknown"
target = "aarch64-apple-darwin"
